### ISSUE TITLE
School CCD enrollment data doesn't have school ID

### ISSUE THREAD

**Issue by barose1** [UrbanInstitute/education-data-package-stata#53]
The "school ccd enrollment" data only has year, grade, race, sex - no school_id or seasch or any other primary key.

**Comment by grahamimac** [comment]
Thanks for reporting @barose1. We're currently working to fix a recent Stata HTTPS error before we can test, confirm, and fix this bug. We apologize for the delay.

**Comment by grahamimac** [comment]
We've fixed our HTTPS bug, and I can replicate the error you are encountering. We have isolated the problem to a missing variable in our metadata endpoint, which is causing the Stata package to drop the variable when it collects it from the API (the data are there, but the metadata for ncessch is missing).

We're working on fixing this as soon as we can. Thanks again for finding this. We apologize for the inconvenience.

**Comment by grahamimac** [comment]
Hi @barose1, the issue you reported on this endpoint is now resolved. The only identifiers we have on the underlying data is ncessch, not school_id or seasch, though, but ncessch should now appear in the "school ccd enrollment" call.

If this is a request for additional identifiers, please let me know. Otherwise, thanks for your patience.

**Comment by vrosenboom** [comment]
Thanks for raising this issue! We've fixed the issue now and ncessch appears when you download the data. I just tested out this command with the stata package:
 educationdata using "school ccd enrollment", sub(year=2014 grade=8)

Please let us know if the issue continues or if you have any other problems! Thank you again.
